version: "3"

services:
  db-postgres:
    ports:
      - "5555:5432"
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile-dev
    volumes:
      - ./nginx/conf/nginx-dev.conf:/etc/nginx/conf.d/default.conf
  auth-service:
    ports:
      - "8000:8000"
  shop-service:
    build:
      context: backend/shop-service
      dockerfile: Dockerfile-dev
    volumes:
      - ./backend/shop-service/src/:/shop-service/src
    environment:
      - GRAPHIQL=true
    ports:
      - "8080:8080"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/public:/frontend/public
      - ./frontend/src:/frontend/src
      - ./frontend/.eslintrc.cjs:/frontend/.eslintrc.cjs
      - ./frontend/index.html:/frontend/index.html
      - ./frontend/tsconfig.json:/frontend/tsconfig.json
      - ./frontend/tsconfig.node.json:/frontend/tsconfig.node.json
      - ./frontend/vite.config.ts:/frontend/vite.config.ts
    ports:
      - "5173:5173"
    command: [ "npm", "run", "dev" ]


