FROM openjdk:19-alpine
WORKDIR /shop-service

COPY build.gradle.kts settings.gradle.kts ./
COPY src ./src

RUN apk add --no-cache gradle

RUN gradle wrapper
RUN chmod +x ./gradlew

EXPOSE 8080
CMD ["sh", "-c", "./gradlew build && java -jar build/libs/shop-service-0.0.1-SNAPSHOT.jar"]